### ISSUE TITLE
Convert all ERB to Slim

### ISSUE THREAD

**Issue by GA114** [GA114/tc359_rails_final#2]
@chrisvfritz

**Comment by chrisvfritz** [comment]
:+1: Some of the nicest Slim I've seen so far! :tada: I think I only see one point for even further improvement, though it's not something you have to fix for acceptance. Lines like:

``` slim
div.field
```

Can actually be shortened to:

``` slim
.field
```

Slim assumes that if you just have an id and/or class(es), then that element should be a div.
