### ISSUE TITLE
Implement registration and sign-in/out

### ISSUE THREAD

**Issue by GA114** [GA114/tc359_rails_final#3]
@chrisvfritz

**Comment by chrisvfritz** [comment]
Is this the latest commit? It looks like [the users_controller actions are empty](https://github.com/GA114/tc359_rails_final/blob/master/app/controllers/users_controller.rb), but I think I remember them being filled out in class.

**Comment by GA114** [comment]
Ah, whoops, I didn't commit.

**Comment by chrisvfritz** [comment]
:+1: Excellent!
